<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="CounterStrikeSharp.API">
      <HintPath>/home/cs2/server/game/csgo/addons/counterstrikesharp/api/CounterStrikeSharp.API.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
